//
// Created by Qi Liu on 2019-04-01.
//

#ifndef EVENTSIMULATIONS_SUPERMARKETSIMULATOR_H
#define EVENTSIMULATIONS_SUPERMARKETSIMULATOR_H


class SupermarketSimulator{

};
#endif //EVENTSIMULATIONS_SUPERMARKETSIMULATOR_H
